apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-pull-model" (include "ollama.fullname" .) | trunc 63 | trimSuffix "-" }}
spec:
  template:
    metadata:
      labels:
        app: {{ printf "%s-pull-model" (include "ollama.fullname" .) | trunc 63 | trimSuffix "-" }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: pull-model
        image: dataopennesscommunity/demo-golden
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
            - name: OLLAMA_HOST
              value: {{ .Values.ollamaHost }}
            - name: OLLAMA_MODEL
              value: {{ .Values.ollamaModel }}
        volumeMounts:
        - name: script-volume
          mountPath: /app
        command: ["python3", "/app/pull_model.py"]
      volumes:
      - name: script-volume
        configMap:
          name: {{ template "ollama.fullname" . }}-python
      restartPolicy: Never