apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hive.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hive.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "hive.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: jdbc
              containerPort: {{ .Values.service.jdbc.port }}
            - name: http
              containerPort: {{ .Values.service.http.port }}
          env:
            - name: SERVICE_NAME
              value: hiveserver2
              
          volumeMounts:
          - name: hive-config-volume
            mountPath: /opt/hive/conf/hive-site.xml  # Mount only hive-site.xml
            subPath: hive-site.xml
      volumes:
      - name: hive-config-volume
        configMap:
          name: {{ include "hive.fullname" . }}
          items:
              - key: hive-site.xml
                path: hive-site.xml