replicaCount: 1

image:
  repository: dataopennesscommunity/demo-golden
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 6005
  targetPort: 6005

ingress:
  enabled: true
  # annotations, hosts, and other configurations go here

sandboxUrl: http://dremio-client.dremio-sandbox-ns.svc.cluster.local:9047
prodUrl: http://dremio-client.dremio-ns.svc.cluster.local:9047
sandboxUsr: dremio
sandboxPw: dremio123
prodUsr: dremio
prodPw: dremio123