replicaCount: 1

image:
  repository: apache/hive
  pullPolicy: Always
  tag: 4.0.1

service:
  type: NodePort
  jdbc:
    port: 10000
    targetPort: 10000
    nodePort: 31000
  http:
    port: 10002
    targetPort: 10002
    nodePort: 31002


