replicaCount: 1

image:
  repository: dataopennesscommunity/demo-react
  pullPolicy: Always
  tag: "latest"

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30030
  
hostIp: HOST_IP
