apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dataset-propagate.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dataset-propagate.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dataset-propagate.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: python-script-volume
              mountPath: /usr/src/app
          command: ["python3"]
          args: ["/usr/src/app/dataset-propagate.py"]
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SANDBOX_URL
              value: {{ .Values.sandboxUrl }}
            - name: PROD_URL
              value: {{ .Values.prodUrl }}
            - name: SANDBOX_USERNAME
              value: admin
            - name: SANDBOX_PASSWORD
              value: admin
            - name: PROD_USERNAME
              value: admin
            - name: PROD_PASSWORD
              value: admin
      volumes:
        - name: python-script-volume
          configMap:
            name: {{ include "dataset-propagate.fullname" . }}
            items:
              - key: dataset-propagate.py
                path: dataset-propagate.py